backend/digikala/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from products.views import home

urlpatterns = [
    path('', home, name='home_view'),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls', namespace='products')),
    path('sellers/', include('sellers.urls', namespace='sellers')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/products/urls.py
from .views import product_list_view, comment_api_response_rest,\
    ProductListView, ProductClassBaseView
from django.urls import path
from .api import ProductDetail, ProductList, ProductListGenericView,\
    ProductDetailGenericView, ProductModelViewSet
from rest_framework import routers

router = routers.SimpleRouter()
router.register(r'products', ProductModelViewSet)

app_name = 'products'
urlpatterns = [
    path('', product_list_view, name='product-list'),
    path('<int:pk>/comments/', comment_api_response_rest, name='comment_api'),
    path('<int:pk>/', ProductClassBaseView.as_view(), name='product_detail'),
    path('category/<slug:slug>/',
         ProductListView.as_view(), name='product_list'),
] + router.urls

backend/sellers/urls.py
app_name = 'sellers'
urlpatterns = [

]

backend/products/models.py
from django.db import models
from django.utils.translation import gettext as _
from django.urls import reverse
from django.conf import settings
from .validators import validate_rate


class Brand(models.Model):
    name = models.CharField(_("Name"), max_length=150)
    en_name = models.CharField(_("English Name"), max_length=150)
    slug = models.SlugField(_("slug"))

    def __str__(self) -> str:
        return self.slug


class MyQuerySet(models.QuerySet):
    def delete(self):
        return self.update(is_active=False)


class NoDeleteManager(models.Manager):
    def get_queryset(self):
        return MyQuerySet(self.model, using=self._db)


class Product(models.Model):
    name = models.CharField(_("Persian Name"), max_length=200)
    en_name = models.CharField(_("English Name"), max_length=200)
    description = models.TextField(_("Description"))
    category = models.ForeignKey("Category",
                                 verbose_name=_("Category"),
                                 on_delete=models.RESTRICT
                                 )
    brand = models.ForeignKey("Brand", verbose_name=_("Brand"),
                              on_delete=models.SET_NULL,
                              null=True,
                              blank=True)
    sellers = models.ManyToManyField("sellers.Seller",
                                     verbose_name=_("Sellers"),
                                     through='SellerProductPrice')
    is_active = models.BooleanField(_("is active"), default=True)
    objects = NoDeleteManager()
    liked_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, blank=True, related_name='liked_products')

    @property
    def default_image(self):
        return self.image_set.filter(is_default=True).first()

    def delete(self, using=None, keep_parents=None):
        self.is_active = False
        self.save()
        return

    @property
    def categories_list(self):
        category_list = []
        current_category = self.category
        while current_category.parent is not None:
            category_list.append(current_category)
            current_category = current_category.parent
        category_list.append(current_category)
        category_list.reverse()
        return category_list

    @property
    def sellers_last_price(self):
        return SellerProductPrice.objects.raw(
            """select * from products_sellerproductprice 
            where product_id = %(id)s
            group by seller_id
            having Max(update_at)""", {"id": self.id})

    @property
    def default_product_seller(self):
        if (self.sellers_last_price):
            return self.sellers_last_price[0]
        return None

    def __str__(self):
        return f"{self.id} {self.name}"

    def get_absolute_url(self):
        return reverse("product_detail", kwargs={"pk": self.pk})


class Category(models.Model):
    name = models.CharField(_("Name"), max_length=50)
    slug = models.SlugField(_("Slug"), unique=True, db_index=True)
    description = models.TextField(_("Description"))
    icon = models.ImageField(
        _("Icon"), upload_to='category_images', null=True, blank=True)
    image = models.ImageField(
        _("Image"), upload_to='category_images', null=True, blank=True)
    parent = models.ForeignKey("self",
                               verbose_name=_("Parent Category"),
                               on_delete=models.SET_NULL,
                               null=True,
                               blank=True
                               )

    @property
    def children(self):
        return self.category_set.all()

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def __str__(self) -> str:
        return self.slug


class Comment(models.Model):
    title = models.CharField(_("Title"), max_length=150)
    text = models.TextField(_("Text"))
    product = models.ForeignKey("Product",
                                verbose_name=_("Product"),
                                on_delete=models.CASCADE,
                                )
    rate = models.PositiveSmallIntegerField(
        _("Rate"), validators=[validate_rate])
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("user"),
        null=True,
        on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Comment")
        verbose_name_plural = _("Comments")

    def __str__(self):
        return f'comment on {self.product.name}'

    def to_dict(self):
        return {
            "id": self.id,
            "user": {'id': self.user.id,
                     'first_name': self.user.first_name
                     }if self.user is not None else None,
            "title": self.title,
            "text": self.text,
            "rate": self.rate
        }


class Image(models.Model):
    name = models.CharField(_("Name"), max_length=50)
    alt = models.CharField(_("Alternative Text"), max_length=100)
    product = models.ForeignKey("Product",
                                verbose_name=_("Product"),
                                on_delete=models.CASCADE)
    image = models.ImageField(_("Image"), upload_to='products',)
    is_default = models.BooleanField(_("Is default image?"), default=False)

    class Meta:
        verbose_name = _("Image")
        verbose_name_plural = _("Images")

    def __str__(self):
        return self.name


class Question(models.Model):
    text = models.TextField(_("Question"))
    user_email = models.EmailField(_("Email"), max_length=254)
    product = models.ForeignKey("Product",
                                verbose_name=_("Product"),
                                on_delete=models.CASCADE
                                )

    class Meta:
        verbose_name = _("Question")
        verbose_name_plural = _("Questions")

    def __str__(self):
        return self.text


class Answer(models.Model):
    text = models.TextField(_("Answer"))
    question = models.ForeignKey("Question",
                                 verbose_name=_("Question"),
                                 on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Answer")
        verbose_name_plural = _("Answers")

    def __str__(self):
        return self.text


class ProductOption(models.Model):
    product = models.ForeignKey("Product",
                                verbose_name=_("Product"),
                                on_delete=models.CASCADE,
                                related_name='product_options'
                                )
    name = models.CharField(_("Attribute"), max_length=200)
    value = models.CharField(_("Value"), max_length=200)

    class Meta:
        verbose_name = _("ProductOption")
        verbose_name_plural = _("ProductOptions")

    def __str__(self):
        return f'{self.product.name} {self.name}'


class SellerProductPrice(models.Model):
    product = models.ForeignKey("Product",
                                verbose_name=_("Product"),
                                related_name='seller_prices',
                                on_delete=models.CASCADE
                                )
    seller = models.ForeignKey(
        "sellers.Seller", verbose_name=_("Seller"), on_delete=models.CASCADE)
    price = models.PositiveIntegerField(_("Price"))
    discount = models.PositiveSmallIntegerField(_("Discount"), default=0)
    create_at = models.DateTimeField(
        _("create at"), auto_now=False, auto_now_add=True)
    update_at = models.DateTimeField(
        _("create at"), auto_now=True,)

    @property
    def discounted_price(self):
        if self.discount > 0:
            return int(self.price - (self.discount * self.price / 100))
        return self.price

    class Meta:
        verbose_name = _("Seller Product Price")
        verbose_name_plural = _("Seller Product Prices")

backend/products/forms.py
from django import forms

from products.models import Comment


# class ProductCommentForm(forms.Form):
#     user_email = forms.EmailField(
#         required=True, label='ایمیل', widget=forms.TextInput(attrs={'class': 'form-control'}))
#     title = forms.CharField(max_length=150, label='عنوان', widget=forms.TextInput(
#         attrs={'class': 'form-control'}))
#     text = forms.CharField(widget=forms.Textarea(
#         attrs={'class': 'form-control'}), label='متن نظر', )
#     rate = forms.IntegerField(max_value=5, min_value=1, label='امتیاز',
#                               widget=forms.TextInput(attrs={'class': 'form-control'}))
#     product_id = forms.IntegerField(widget=forms.HiddenInput())

#     def clean_product_id(self):
#         product_id = self.cleaned_data['product_id']
#         query = Product.objects.filter(pk=product_id)
#         if not query.exists():
#             raise ValidationError({"password": "the product id is invalid"})
#         return product_id

class ProductCommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('user',)
        widgets = {
            "title": forms.TextInput(attrs={'class': 'form-control'}),
            "text": forms.Textarea(attrs={'class': 'form-control', }),
            "rate": forms.NumberInput(attrs={'class': 'form-control'}),
            "product": forms.HiddenInput(),
        }
        labels = {
            "title": "عنوان",
            "text": "متن",
            "rate":  "امتیاز",
        }

    def save(self, commit: bool = ...):
        return super().save(commit)

backend/products/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404, redirect
from products.forms import ProductCommentModelForm
from .models import Product, Category, Comment
import json
from django.views import View
from django.views.generic import ListView, DetailView
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .serializer import CommentModelSerializer
# Create your views here.


def product_list_view(request):
    page = int(request.GET.get('page', 1))
    query = Product.objects.all()
    q = request.GET.get('q', '')
    if q:
        query = query.filter(name__contains=q)
    page_size = 10
    products = query[(page-1) * page_size:page*page_size]
    context = {"products": products}

    return render(
        template_name='products/product-list.html',
        request=request,
        context=context,
    )


class ProductDetailView(DetailView):
    model = Product
    queryset = Product.objects.exclude(is_active=False)


class ProductClassBaseView(View):
    form_class = ProductCommentModelForm
    template_name = "products/product_detail.html"

    def get(self, request, pk, *args, **kwargs):
        p = get_object_or_404(Product.objects.select_related(
            'category'), pk=pk)
        form = self.form_class(initial={'product': p})
        context = {
            "default_product_seller": p.sellers_last_price[0],
            "product": p,
            "product_sellers": p.sellers_last_price,
            "comment_counts": p.comment_set.all().count(),
            'comment_form': form
        }
        return render(request, self.template_name, context)

    def post(self, request, pk, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.save()
        return redirect('products:product_detail', pk=pk)


def product_detail_view(request, pk):
    p = get_object_or_404(Product.objects.select_related(
        'category').prefetch_related("comment_set"), pk=pk)

    if request.method == "GET":
        form = ProductCommentModelForm(initial={'product': p})
    elif request.method == 'POST':
        form = ProductCommentModelForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.save()
            return redirect('products:product_detail', pk=pk)
    context = {
        "default_product_seller": p.sellers_last_price[0],
        "product": p,
        "product_sellers": p.sellers_last_price,
        "comments": p.comment_set.all(),
        "comment_counts": p.comment_set.all().count(),
        'comment_form': form
    }
    return render(
        template_name='products/product_detail.html',
        request=request,
        context=context
    )


def home(request):
    query = Product.objects.all()
    most_off_products = query
    most_sell = query
    most_recent = query
    context = {
        "most_off_products": most_off_products,
        "most_sell": most_sell,
        "most_recent": most_recent,
        "banners": [],
    }

    return render(
        template_name='products/index.html',
        request=request,
        context=context
    )


class ProductListView(ListView):
    model = Product
    context_object_name = "product_list"
    queryset = Product.objects.exclude(is_active=False)

    def get_queryset(self) -> QuerySet[Any]:
        query = super().get_queryset()
        category = Category.objects.get(slug=self.kwargs['slug'])
        self.category = category
        query = query.filter(
            category__slug__in=[self.kwargs['slug'], *category.children],
            name__contains=self.request.GET.get('search', ''))
        return query

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context["category"] = self.category
        return context


@csrf_exempt
def comment_api_response(request, pk):
    if request.method == 'GET':
        comments = Comment.objects.filter(product_id=pk).select_related('user')
        comment_list = []
        for comment in comments:
            comment_list.append(comment.to_dict())
        context = {
            "result": comment_list,
            "count": comments.count(),
        }
        return HttpResponse(content=json.dumps(context),
                            content_type='application/json')

    else:
        form = ProductCommentModelForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.product_id = pk
            comment.save()
            context = comment.to_dict()
            return HttpResponse(content=json.dumps(context),
                                content_type='application/json')
        else:
            return HttpResponse(content=json.dumps({'message': "error"}),
                                content_type='application/json', status=400)


@api_view(["POST", "GET"])
def comment_api_response_rest(request, pk):
    if request.method == 'GET':
        comments = Comment.objects.filter(product_id=pk).select_related('user')
        serializer = CommentModelSerializer(instance=comments, many=True)
        return Response(data=serializer.data)
    else:
        serializer = CommentModelSerializer(data=request.data)
        if serializer.is_valid(raise_exception=True):
            serializer.save()
            return Response(data=serializer.data, status=201)

backend/products/templates/products/product_detail.html
{% extends "base/base.html" %}
{% block title %}
  دی‌جی کالا | {{ product.name }}
{% endblock title %}
{% block main %}
  <div class="container">
    <div class="row">
      <div id="page-content" class="col-12">
        <div id="breadcrump" class="row px-3">
          <ul>
            <li>
              <a href='{% url "home_view" %}'>فوکالا</a>
            </li>
            {% for category in product.categories_list %}
              <li>
                <a href="{% url 'products:product_list' slug=category.slug %}">{{ category.name }}</a>
              </li>
            {% endfor %}
          </ul>
        </div>
        <div id="product-single" class="row">
          <div class="product-image col-12 col-md-6 col-lg-4 p-0">
            <img class="slide-item"
                 src="{{ product.default_image.image.url }}"
                 alt="{{ product.name }}" />
          </div>
          <div class="product-data col-12 col-md-6 col-lg-4">
            <h1 class="product-title">{{ product.name }}</h1>
            <div class="product-meta row">
              <span class="star-rate col-6"><i class="fas fa-star"></i> امتیاز: 3.9 از 5</span>
              <span class="user-comment-count col-6">{{ comment_counts }} دیدگاه کاربران</span>
              <span class="product-category col-6">دسته بندی:
                <a href="#" title="دستمال کاغذی">{{ product.category.name }}</a></span>
              <span class="product-brand col-6">برند: <a href="#" title="نانسی">{{ product.brand.name }}</a></span>
              <div class="product-description">
                <p>{{ product.description }}</p>
              </div>
            </div>
          </div>
          <div class="product-add-cart col-12 col-lg-4">
            <div class="box-wrap">
              <div class="product-seller">
                فروشنده محصول: {{ default_product_seller.seller.name }}
                <br />
                <span>رضایت خرید: 98 درصد</span>
              </div>
              <div class="product-guarantee">گارانتی اصالت و سلامت فیزیکی کالا</div>
              <div class="product-price">
                {% if default_product_seller.discount %}
                  قیمت: <del>{{ default_product_seller.price }}</del> <span>{{ default_product_seller.discounted_price }}
                تومان</span>
              {% else %}
                <span>{{ default_product_seller.discounted_price }} تومان</span>
              {% endif %}
            </div>
            <button href="#"
                    class="btn btn-cart"
                    onclick="addProductToCart({{ default_product_seller.id }} , {{ default_product_seller.price }} ,{{ default_product_seller.discounted_price }})">
              <i class="fas fa-plus"></i> افزودن به سبد
            </button>
          </div>
        </div>
      </div>
    </div>
    <div id="product-sellers" class="col-12">
      {% for s in product_sellers %}
        <div class="row">
          <div class="col-4">
            <div class="product-seller">
              <div>{{ s.seller.name }}</div>
              <span>رضایت خرید: 98 درصد</span>
            </div>
          </div>
          <div class="col-4">
            <div class="product-price">
              <div class="product-price">
                {% if s.discount %}
                  قیمت: <del>{{ s.price }}</del> <span>{{ s.discounted_price }} تومان</span>
                {% else %}
                  <span>{{ s.discounted_price }} تومان</span>
                {% endif %}
              </div>
            </div>
          </div>
          <div class="col-4">
            <button onclick="addProductToCart({{ s.id }} , {{ s.price }} ,{{ s.discounted_price }})"
                    class="btn btn-cart">
              <i class="fas fa-plus"></i> افزودن به سبد
            </button>
          </div>
        </div>
      {% endfor %}
    </div>
    <div id="product-comments" class="col-12">
      <div class="row card">
        {% if request.user.is_authenticated %}
          <div class="col-12 card-body">
            <form id="comment_form" method="post">
              {% include "components/forms.html" with form=comment_form %}
              {% csrf_token %}
              <input type="submit" value="ثبت نظر" class="btn btn-primary">
            </form>
          </div>
        {% endif %}
        <div id='comment-list' class="row card"></div>
        <!-- {% for comment in comments %}
          <div class="col-12">
            <h5>{{ comment.title }}</h5>
            <span>{{ comment.user.email }}</span>
            <p>{{ comment.text }}</p>
          </div>
        {% endfor %} -->
      </div>
    </div>
  </div>
</div>
{% endblock main %}
{% block jsscript %}
  <script>
  function addProductToCart(sellerId, price, discounted_price) {
    const product = {
      id: {{ product.id }},
  image: "{{product.default_image.image.url}}",
    price,
    discounted_price,
    name: '{{product.name}}',
      sellerId
      }
  cartStorageAddItem(product)
    }

  </script>
  <script>
  document.addEventListener("DOMContentLoaded", async function (event) {
    //we ready baby
    const response  = await fetch("{% url 'products:comment_api'  pk=product.id  %}")
    const data = await response.json()
    const root = document.getElementById('comment-list')
      for(item of data){
        root.innerHTML += (`<div class="col-12">
          <div>${item.title}</div> 
          <div>${item.text}<div> 
          </div>`)
      }
    })
  </script>
  <script>
    const form = document.getElementById('comment_form')
    form.addEventListener('submit',async function(event){
      event.preventDefault()
      const form_data = new FormData(event.target)
      const js_data= Object.fromEntries(form_data.entries())
      const res = await fetch("{% url 'products:comment_api'  pk=product.id  %}" , {
        headers: {
          "X-CSRFToken": "{{csrf_token}}",
          'Accept': 'application/json',
          'Content-Type': 'application/json;charset=UTF-8'
          
        },
        credentials: "same-origin",
        method:"POST",
        body: JSON.stringify(js_data)
      })
      const data = await res.json()
      const root = document.getElementById('comment-list')
      root.innerHTML += (`<div class="col-12">
        <div>${data.title}</div> 
        <div>${data.text}<div> 
        </div>`)
    })
      
  </script>
{% endblock jsscript %}

backend/products/templates/products/product_list.html
{% extends 'base/base.html' %}
{% block title %}
    {{ category.name }}
{% endblock title %}
{% block main %}
    <div class="container">
        <div class="row">
            <aside id="widget-sidebar" class="col-12 col-md-5 col-lg-3 p-0 pl-md-3">
                <div id="category-widget" class="sidebar-widget">
                    <h4 class="widget-title">دسته بندی محصولات</h4>
                    <div class="widget-content">
                        <ul>
                            <li>
                                <a href="#pageSubmenu1" data-toggle="collapse" aria-expanded="false"><i class="fas fa-angle-left"></i> کالاهای اساسی و
                                خوار و بار</a>
                                <ul class="collapse p-0" id="pageSubmenu1">
                                    <li>
                                        <a href="#">نان</a>
                                    </li>
                                    <li>
                                        <a href="#">برنج</a>
                                    </li>
                                    <li>
                                        <a href="#">روغن</a>
                                    </li>
                                    <li>
                                        <a href="#">قند و شکر</a>
                                    </li>
                                    <li>
                                        <a href="#">حبوبات و سویا</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="active">
                                <a href="#pageSubmenu2" data-toggle="collapse" aria-expanded="true"><i class="fas fa-angle-left"></i> لبنیات</a>
                                <ul class="collapse show p-0" id="pageSubmenu2">
                                    <li>
                                        <a href="#">شیر</a>
                                    </li>
                                    <li>
                                        <a href="#">کره حیوانی و گیاهی</a>
                                    </li>
                                    <li>
                                        <a href="#">دوغ</a>
                                    </li>
                                    <li>
                                        <a href="#">ماست</a>
                                    </li>
                                    <li>
                                        <a href="#">پنیر</a>
                                    </li>
                                    <li class="active">
                                        <a href="#">خامه</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
                <div id="search-widget" class="sidebar-widget">
                    <h4 class="widget-title">جستجوی محصول</h4>
                    <div class="widget-content">
                        <form action="{% url 'products:product_list' slug=category.slug %}"
                              data-action=""
                              id="frmSearch-side"
                              autocomplete="off"
                              class="search-box">
                            <div class="input-group">
                                <input autocomplete="off"
                                       name="search"
                                       type="text"
                                       id="search-field-side"
                                       class="search-field form-control"
                                       placeholder="جستجو در این دسته بندی">
                                <div class="input-group-append">
                                    <button class="btn btn-gradient-primary" type="submit">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="search-result search-box-dropdown mt-8"></div>
                        </form>
                    </div>
                </div>
                <div id="filter-widget" class="sidebar-widget">
                    <h4 class="widget-title">برند محصول</h4>
                    <div class="widget-content">
                        <form action=""
                              data-action=""
                              id="filter-side"
                              autocomplete="off"
                              class="filter-box">
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input" id="kalleh">
                                <label class="custom-control-label" for="kalleh">کاله</label>
                            </div>
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input" id="mihan">
                                <label class="custom-control-label" for="mihan">میهن</label>
                            </div>
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input" id="choopan">
                                <label class="custom-control-label" for="choopan">چوپان</label>
                            </div>
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input" id="damdaran">
                                <label class="custom-control-label" for="damdaran">دامداران</label>
                            </div>
                        </form>
                    </div>
                </div>
            </aside>
            <div id="page-content" class="col-12 col-md-7 col-lg-9">
                <div id="breadcrump" class="row px-3">فوکالا / لبنیات / خامه</div>
                <div id="product-sort" class="row px-3">
                    <div class="sort-title">
                        <i class="fas fa-bars"></i> مرتب سازی بر اساس:
                    </div>
                    <span>پرفروش‌ترین‌</span> <span>محبوب‌ترین</span> <span class="active">جدیدترین</span>
                    <span>ارزان‌ترین</span> <span>گران‌ترین</span> <span>سریع‌ترین ارسال</span>
                </div>
                <div id="products-grid" class="row">
                    {% for product in product_list %}
                        <div class='col-6 col-lg-4 col-xl-3'>{% include "components/product-card.html" %}</div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}