backend/accounts/urls.py
from django.urls import path, include
from .views import login_view, user_register_view, user_info_view,\
    logout_view, user_comments_view, MyLoginView, get_users_list,\
    UserUpdateView
from .api import user_change_password, user_info, user_register

app_name = 'accounts'
urlpatterns = [
    path('login/', MyLoginView.as_view(), name='login_view'),
    path('register/', user_register_view, name='register_view'),
    path('profile/', UserUpdateView.as_view(), name='user_info_view'),
    path('profile/comments', user_comments_view, name='user_comments_view'),
    path('logout/', logout_view, name='user_logout_view'),
    path('users-list/', get_users_list, name='users_list'),
    path('api/change-password/', user_change_password, name='api-password-change'),
    path('api/user-info/', user_info, name='api-user-info'),
    path('api/register/', user_register, name='api-register'),
]

backend/digikala/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from products.views import home

urlpatterns = [
    path('', home, name='home_view'),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls', namespace='products')),
    path('sellers/', include('sellers.urls', namespace='sellers')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/products/urls.py
from .views import product_list_view, comment_api_response_rest,\
    ProductListView, ProductClassBaseView
from django.urls import path
from .api import ProductDetail, ProductList, ProductListGenericView,\
    ProductDetailGenericView, ProductModelViewSet
from rest_framework import routers

router = routers.SimpleRouter()
router.register(r'products', ProductModelViewSet)

app_name = 'products'
urlpatterns = [
    path('', product_list_view, name='product-list'),
    path('<int:pk>/comments/', comment_api_response_rest, name='comment_api'),
    path('<int:pk>/', ProductClassBaseView.as_view(), name='product_detail'),
    path('category/<slug:slug>/',
         ProductListView.as_view(), name='product_list'),
] + router.urls

backend/sellers/urls.py
app_name = 'sellers'
urlpatterns = [

]

backend/templates/components/footer.html
{% load static %}
<footer>
    <div class="container-fluid">
        <div class="row">
            <div class="footer-slogan col-12 text-center">فوکالا، تجربه خرید آنلاین به یادماندنی</div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div id="fookala-widget" class="footer-widget col-6 col-xl-2">
                <h4 class="widget-title">فوکالا</h4>
                <div class="widget-content">
                    <ul>
                        <li>بلاگ فوکالا</li>
                        <li>درباره فوکالا</li>
                        <li>تماس با ما</li>
                        <li>همکاری با ما</li>
                        <li>ثبت‌نام سوپرمارکت</li>
                    </ul>
                </div>
            </div>
            <div id="customers-widget" class="footer-widget col-6 col-xl-2">
                <h4 class="widget-title">مشتریان</h4>
                <div class="widget-content">
                    <ul>
                        <li>حساب کاربری</li>
                        <li>تاریخچه سفارشات</li>
                        <li>شرایط حمل و نقل</li>
                        <li>شرایط مرجوعی</li>
                        <li>حریم خصوصی</li>
                    </ul>
                </div>
            </div>
            <div id="contact-widget" class="footer-widget col-12 col-sm-6 col-xl-4">
                <h4 class="widget-title">اطلاعات تماس</h4>
                <div class="widget-content">
                    <div class="address"><i class="fas fa-map-marker-alt"></i> تهران - شهرک غرب، بلوار فرحزادی،
                        خیابان حافظی، پلاک 48، واحد 8</div>
                    <div class="telephone ltr text-left"><i class="fas fa-phone"></i> 021 - 22139201</div>
                    <div class="email ltr text-left"><i class="fas fa-envelope"></i> info[at]fookala[dot]com
                    </div>
                </div>
            </div>
            <div id="logos-widget" class="footer-widget col-12 col-sm-6 col-xl-4">
                <h4 class="widget-title">اطمینان از خرید</h4>
                <div class="widget-content">
                    <img src="{% static 'images/logos/logo-e.jpg' %}" alt="enamad-logo" />
                    <img src="{% static 'images/logos/logo-s.jpg' %}" alt="samandehi-logo" />
                    <img src="{% static 'images/logos/logo-k.jpg' %}" alt="kasbokar-logo" />
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="copyright col-12 text-center"><i class="far fa-copyright"></i> ۱۳۸۱-۱۳۹۹ کلیه حقوق محفوظ است.
            </div>
        </div>
    </div>
</footer>

backend/templates/components/forms.html
{% csrf_token %}
{{ form.non_field_errors }}
{% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
{# Include the visible fields #}
{% for field in form.visible_fields %}
    <div class="form-group">
        {{ field.label_tag }} {{ field }}
        {{ field.errors }}
    </div>
{% endfor %}
{% for inline in form.inlines %}
    <div class='card mt-2'>
        <div class="card-body">
            {% for field in inline %}
                <div class="form-group">
                    {{ field.label_tag }} {{ field }}
                    {{ field.errors }}
                </div>
            {% endfor %}
        </div>
    </div>
{% endfor %}

backend/templates/components/header.html
{% load static %}
<header>
    <nav id="sidemenu" class="sidebar">
        <div class="dismiss">
            <i class="fas fa-arrow-right"></i>
        </div>
        <div class="sidebar-header">
            <h3>
                <a class="navbar-brand p-0 m-0" href="#">
                    <img src="{% static 'images/fookala-farsi.svg' %}" width="115" height="36">
                </a>
            </h3>
        </div>
        <ul class="p-0 components">
            <p>سوپر مارکت سریع</p>
            <li class="active">
                <a href={% url 'home_view' %}>صفحه اصلی</a>
            </li>
            <li>
                <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false">انواع آشامیدنی</a>
                <ul class="collapse p-0" id="pageSubmenu">
                    <li>
                        <a href="#">نوشیدنی گرم</a>
                    </li>
                    <li>
                        <a href="#">نوشیدنی سرد</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#">درباره فوکالا</a>
            </li>
            <li>
                <a href="#">تماس با فوکالا</a>
            </li>
        </ul>
    </nav>
    <nav class="navbar navbar-light bg-light fixed-top rtl px-2">
        <div class="container px-0 px-lg-1">
            <button id="sidemenuCollapse"
                    class="navbar-toggler"
                    type="button"
                    title="مشاهده منو">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand p-0 m-0" href={% url 'home_view' %}>
                <img src="{% static 'images/fookala-farsi.svg' %}"
                     alt='logo'
                     width="115"
                     height="36">
            </a>
            <div class="searchform mx-auto w-50 w-60-lg px-0 px-lg-1">
                <form action="/search"
                      data-action=""
                      id="frmSearch"
                      autocomplete="off"
                      class="search-box">
                    <div class="input-group">
                        <input autocomplete="off"
                               name="keyword"
                               type="text"
                               id="search-field"
                               class="form-control"
                               placeholder="برند، کالا و یا دسته بندی مورد نظر">
                        <div class="input-group-append">
                            <button class="btn btn-gradient-primary" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                    <div class="search-result search-box-dropdown mt-8"></div>
                </form>
            </div>
            <div class="nav-btn">
                <button id="location"
                        class="navbar-toggler location-btn"
                        type="button"
                        title="تعیین موقعیت">
                    <span class="cart-toggler-icon">
                        <i class="fas fa-map-marker-alt"></i>
                    </span>
                </button>
                <a id="account"
                   class="navbar-toggler account-btn"
                   type="button"
                   href="{% if user.is_authenticated %}{% url 'accounts:user_info_view' %}{% else %}{% url 'accounts:login_view' %}{% endif %}"
                   title="محیط">
                    <span class="cart-toggler-icon">
                        <i class="fas fa-user"></i>
                    </span>
                </a>
                <button id="minicartCollapse"
                        class="navbar-toggler mini-cart"
                        type="button"
                        title="مشاهده سبد خرید">
                    <span class="cart-toggler-icon">
                        <i class="fas fa-shopping-cart"></i>
                    </span>
                    <span class="cart-total">14</span>
                </button>
            </div>
        </div>
    </nav>
    {% include 'components/mini-card.html' %}
</header>

backend/templates/components/mini-card.html
{% load static %}
<nav id="minicart" class="sidebar">
    <div class="dismiss">
        <i class="fas fa-arrow-left"></i>
    </div>
    <div class="sidebar-header">
        <h3>سبد خرید</h3>
    </div>
    <div class="row m-0 totalcart total">
        <div class="col-6 text-right">مجموع خرید:</div>
        <div class="col-6 text-left total-value">25000 تومان</div>
    </div>
    <div class="row m-0 totaloff total">
        <div class="col-6 text-right">مجموع تخفیف:</div>
        <div class="col-6 text-left total-value">1000 تومان</div>
    </div>
    <ul class="p-0 components">
        <li>
            <div class="product-removal">
                <button class="remove-product">
                    <i class="fas fa-window-close jhfg"></i>
                </button>
            </div>
            <a href="#" title="">
                <img src="{% static 'images/products/1.jpg' %}" width="70" height="70" />
            </a>
            <div class="product-title mb-1">
                <a href="#" title="">دستمال کاغذی سافت‌لن</a>
            </div>
            <div class="product-price">
                <del>126,000</del>
                <br>
                <span>170,000 تومان</span>
            </div>
            <div class="product-quantity">
                <div class="input-group">
                    <span class="input-group-btn">
                        <button type="button"
                                class="quantity-left-minus btn btn-danger btn-number"
                                data-type="minus"
                                data-field="">
                            <i class="fas fa-minus"></i>
                        </button>
                    </span>
                    <input type="text"
                           class="quantity"
                           name="quantity"
                           class="form-control input-number"
                           value="10"
                           min="1"
                           max="100">
                    <span class="input-group-btn">
                        <button type="button"
                                class="quantity-right-plus btn btn-success btn-number"
                                data-type="plus"
                                data-field="">
                            <i class="fas fa-plus"></i>
                        </button>
                    </span>
                </div>
            </div>
        </li>
        <li>
            <div class="product-removal">
                <button class="remove-product">
                    <i class="fas fa-window-close jhfg"></i>
                </button>
            </div>
            <a href="#" title="">
                <img src="{% static 'images/products/2.jpg' %}" width="70" height="70" />
            </a>
            <div class="product-title mb-1">
                <a href="#" title="">دستمال کاغذی سافت‌لن</a>
            </div>
            <div class="product-price">
                <del>126,000</del>
                <br>
                <span>170,000 تومان</span>
            </div>
            <div class="product-quantity">
                <div class="input-group">
                    <span class="input-group-btn">
                        <button type="button"
                                class="quantity-left-minus btn btn-danger btn-number"
                                data-type="minus"
                                data-field="">
                            <i class="fas fa-minus"></i>
                        </button>
                    </span>
                    <input type="text"
                           class="quantity"
                           name="quantity"
                           class="form-control input-number"
                           value="10"
                           min="1"
                           max="100">
                    <span class="input-group-btn">
                        <button type="button"
                                class="quantity-right-plus btn btn-success btn-number"
                                data-type="plus"
                                data-field="">
                            <i class="fas fa-plus"></i>
                        </button>
                    </span>
                </div>
            </div>
        </li>
    </ul>
    <button class="checkout">
        ثبت سفارش <i class="fas fa-credit-card"></i>
    </button>
</nav>

backend/templates/components/product-card.html
<a href="{% url 'products:product_detail' pk=product.id %}">
    <div class="card">
        <img class="slide-item"
             src="{{ product.default_image.image.url }}"
             alt="{{ product.name }}" />
        <div class="card-body">
            <h5 class="card-title">{{ product.name }}</h5>
            <div class="product-price">
                {% if product.default_product_seller.discount %}
                    قیمت: <del>{{ product.default_product_seller.price }}</del>
                    <span>{{ product.default_product_seller.discounted_price }}
                    تومان</span>
                {% else %}
                    <span>{{ product.default_product_seller.discounted_price }} تومان</span>
                {% endif %}
            </div>
            <button href="#" class="btn btn-cart">
                <i class="fas fa-plus"></i>
                افزودن به سبد
            </button>
        </div>
    </div>
</a>

backend/templates/components/product-list-carousel.html
<section id="top-sale" class="carousel-box px-1 px-lg-0">
    <div class="container">
        <div class="row px-1">
            <div class="box-wrap">
                <div class="title-wrap col-12">
                    <h4>پرفروش‌ترین</h4> <a href="#"><span>(مشاهده همه)</span></a>
                </div>
                <div class="carousel-container ltr col-12 p-1">
                    <div class="products-carousel owl-carousel">
                        <div class="card">
                            <img class="slide-item" src="images/products/1.jpg" alt="" />
                            <div class="card-body">
                                <h5 class="card-title">دستمال کاغذی سافتلن</h5>
                                <div class="product-price"><del>7,000</del><span>6,000 تومان</span>
                                </div>
                                <button href="#" class="btn btn-cart"><i class="fas fa-plus"></i> افزودن به
                                    سبد</button>
                            </div>
                        </div>
                        <div class="card">
                            <img class="slide-item" src="images/products/2.jpg" alt="" />
                            <div class="card-body">
                                <h5 class="card-title">کرم روشن کننده بورژوا</h5>
                                <div class="product-price"><del>8,500</del><span>7,000 تومان</span>
                                </div>
                                <button href="#" class="btn btn-cart"><i class="fas fa-plus"></i> افزودن به
                                    سبد</button>
                            </div>
                        </div>
                        <div class="card">
                            <img class="slide-item" src="images/products/3.jpg" alt="" />
                            <div class="card-body">
                                <h5 class="card-title">کرم ضد آفتاب سینره</h5>
                                <div class="product-price"><del>9,000</del><span>8,000 تومان</span>
                                </div>
                                <button href="#" class="btn btn-cart"><i class="fas fa-plus"></i> افزودن به
                                    سبد</button>
                            </div>
                        </div>
                        <div class="card">
                            <img class="slide-item" src="images/products/4.jpg" alt="" />
                            <div class="card-body">
                                <h5 class="card-title">کرم نرم کننده پوست سینره</h5>
                                <div class="product-price"><del>19,500</del><span>17,000 تومان</span>
                                </div>
                                <button href="#" class="btn btn-cart"><i class="fas fa-plus"></i> افزودن به
                                    سبد</button>
                            </div>
                        </div>
                        <div class="card">
                            <img class="slide-item" src="images/products/5.jpg" alt="" />
                            <div class="card-body">
                                <h5 class="card-title">اسپری خوشبو کننده آنیکا</h5>
                                <div class="product-price"><del>25,300</del><span>24,000 تومان</span>
                                </div>
                                <button href="#" class="btn btn-cart"><i class="fas fa-plus"></i> افزودن به
                                    سبد</button>
                            </div>
                        </div>
                        <div class="card">
                            <img class="slide-item" src="images/products/6.jpg" alt="" />
                            <div class="card-body">
                                <h5 class="card-title">کرم ذغال ضدعفونی کننده آنیکا</h5>
                                <div class="product-price"><del>46,500</del><span>45,000 تومان</span>
                                </div>
                                <button href="#" class="btn btn-cart"><i class="fas fa-plus"></i> افزودن به
                                    سبد</button>
                            </div>
                        </div>
                        <div class="card">
                            <img class="slide-item" src="images/products/7.jpg" alt="" />
                            <div class="card-body">
                                <h5 class="card-title">چای سیاه ارل گری اویلا</h5>
                                <div class="product-price"><del>29,000</del><span>27,000 تومان</span>
                                </div>
                                <button href="#" class="btn btn-cart"><i class="fas fa-plus"></i> افزودن به
                                    سبد</button>
                            </div>
                        </div>
                        <div class="card">
                            <img class="slide-item" src="images/products/8.jpg" alt="" />
                            <div class="card-body">
                                <h5 class="card-title">روغن خوراکی مصرف خانوار - جامد 500 گرمی</h5>
                                <div class="product-price"><del>36,100</del><span>35,000 تومان</span>
                                </div>
                                <button href="#" class="btn btn-cart"><i class="fas fa-plus"></i> افزودن به
                                    سبد</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

backend/templates/components/slider.html
<section id="slide" class="px-1 px-lg-0">
    <div class="container">
        <div class="row">
            <div class="slide-container ltr col-12 col-lg-8 p-1">
                <div class="main-slide owl-carousel">
                    <img class="slide-item" src="images/slides/1.jpg" alt="" />
                    <img class="slide-item" src="images/slides/2.jpg" alt="" />
                </div>
            </div>
            <div class="banners-container col-12 col-lg-4">
                <div class="row">
                    <div class="col-lg-12 col-6 h-50 banner-item p-1"><img src="images/slides/3.jpg" alt="" />
                    </div>
                    <div class="col-lg-12 col-6 h-50 banner-item p-1"><img src="images/slides/4.jpg" alt="" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>