backend/accounts/urls.py
from django.urls import path, include
from .views import login_view, user_register_view, user_info_view,\
    logout_view, user_comments_view, MyLoginView, get_users_list,\
    UserUpdateView
from .api import user_change_password, user_info, user_register

app_name = 'accounts'
urlpatterns = [
    path('login/', MyLoginView.as_view(), name='login_view'),
    path('register/', user_register_view, name='register_view'),
    path('profile/', UserUpdateView.as_view(), name='user_info_view'),
    path('profile/comments', user_comments_view, name='user_comments_view'),
    path('logout/', logout_view, name='user_logout_view'),
    path('users-list/', get_users_list, name='users_list'),
    path('api/change-password/', user_change_password, name='api-password-change'),
    path('api/user-info/', user_info, name='api-user-info'),
    path('api/register/', user_register, name='api-register'),
]

backend/digikala/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from products.views import home

urlpatterns = [
    path('', home, name='home_view'),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls', namespace='products')),
    path('sellers/', include('sellers.urls', namespace='sellers')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/sellers/urls.py
app_name = 'sellers'
urlpatterns = [

]

backend/accounts/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.core.mail import send_mail
from django.contrib.auth.hashers import make_password

# Create your models here.


class UserManager(BaseUserManager):

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email, and password.
        """
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self,  email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin,):
    first_name = models.CharField(_("first name"), max_length=150, blank=True)
    last_name = models.CharField(_("last name"), max_length=150, blank=True)
    email = models.EmailField(_("email address"), unique=True)
    mobile = models.CharField(
        _("mobile number"), max_length=11, unique=True, blank=True, null=True)
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_(
            "Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = "%s %s" % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

backend/accounts/forms.py
from typing import Any, Dict
from django import forms
from django.contrib.auth import authenticate
from .models import User
from django.contrib.auth.forms import AuthenticationForm, UsernameField


class MyAuthenticationForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(
        attrs={"autofocus": True, 'class': "form-control"}), label="نام کاربری")
    password = forms.CharField(
        label="کلمه عبور",
        strip=False,
        widget=forms.PasswordInput(
            attrs={"autocomplete": "current-password", 'class': "form-control"}),
    )


class UserLoginForm(forms.Form):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(UserLoginForm, self).__init__(*args, **kwargs)

    email = forms.EmailField(
        widget=forms.EmailInput({"class": "form-control"}), required=True)
    password = forms.CharField(
        widget=forms.PasswordInput({"class": "form-control"}), required=True)

    def clean(self) -> Dict[str, Any]:
        clean_data = super().clean()
        user = authenticate(
            self.request,
            username=clean_data["email"],
            password=clean_data['password'])

        if user is not None:
            clean_data['user'] = user
            return clean_data
        else:
            raise forms.ValidationError('credential is invalid')


class UserRegisterFrom(forms.ModelForm):
    password1 = forms.CharField(
        widget=forms.PasswordInput({"class": "from-control"}),
        label='کلمه عبور')
    password2 = forms.CharField(
        widget=forms.PasswordInput({"class": "from-control"}),
        label='تکرار کلمه عبور')

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
            'mobile',
            'password1',
            'password2'
        )

    def clean(self) -> Dict[str, Any]:
        cleaned_data = super().clean()
        password1 = cleaned_data.pop('password1', None)
        password2 = cleaned_data.pop('password2', None)
        if password1 != password2:
            self.add_error('password2', forms.ValidationError(
                'در وارد کردن کلمه عبور دقت کنید', code='invalid'))
            # raise forms.ValidationError(
            #     'در وارد کردن کلمه عبور دقت کنید', code='invalid')

        cleaned_data.setdefault('password', password1)
        return cleaned_data

    def save(self, commit: bool = ...) -> Any:
        user = super().save(commit)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

backend/accounts/views.py
from typing import Any, Optional
from django.db import models
from django.shortcuts import render, redirect
from django.urls import reverse
from accounts.forms import UserLoginForm, UserRegisterFrom,\
    MyAuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.forms import AuthenticationForm
from products.models import Comment
from .models import User
# Create your views here.
from django.views.generic import ListView, DetailView, CreateView,\
    DeleteView, UpdateView


class MyLoginView(LoginView):
    template_name = 'accounts/login_view.html'
    authentication_form = MyAuthenticationForm


class UserUpdateView(UpdateView):
    model = User
    fields = ['first_name', 'last_name', 'mobile']
    queryset = User.objects.all()
    template_name = 'accounts/user_info.html'

    def get_object(self, queryset=None):
        return self.request.user


def login_view(request):
    if request.method == 'GET':
        form = AuthenticationForm()
    else:

        form = AuthenticationForm(data=request.POST, request=request)
        if form.is_valid():
            login(request=request, user=form.get_user())
            next = request.GET.get('next', reverse('accounts:user_info_view'))
            return redirect(next)
    context = {
        "form": form,
        "next": request.GET.get('next', reverse('accounts:user_info_view'))
    }
    return render(request, 'accounts/login_view.html', context)


def user_register_view(request):
    status = 200
    if request.method == 'GET':
        form = UserRegisterFrom()
    else:
        form = UserRegisterFrom(request.POST,)
        if form.is_valid():
            user = form.save(commit=True)
            login(request=request, user=user)
            return redirect('accounts:user_info_view')
        else:
            status = 400
    context = {
        "form": form
    }
    return render(request, 'accounts/register_view.html', context, status=status)


@login_required()
def user_info_view(request):
    return render(request, 'accounts/user_info.html', {
        "user": request.user
    })


def logout_view(request):
    logout(request)
    return redirect('accounts:user_info_view')


@login_required()
def user_comments_view(request):
    query = Comment.objects.filter(user=request.user)
    return render(request, 'accounts/user_comments.html', {
        'comments': query
    })


def is_staff_user(user):
    return user.is_staff and user.is_active


@user_passes_test(is_staff_user)
@permission_required('accounts.view_user', raise_exception=True)
@login_required()
def get_users_list(request):
    users = User.objects.all()
    return render(request, 'accounts/view_all_users.html', {
        'users_list': users
    })

backend/accounts/templates/accounts/login_view.html
{% extends "base/base.html" %}
{% block title %}
    {{ product.name }}
{% endblock title %}
{% block main %}
    <div class="container">
        <div class="row">
            <div id="page-content" class="col-12 col-md-6 col-lg-4 mx-auto">
                <div class="card-body">
                    <form action="{% url 'accounts:login_view' %}?next={{ next }}"
                          method="post">
                        {% include "components/forms.html" %}
                        <input type="submit" value="login" class="btn btn-primary">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock main %}

backend/accounts/templates/accounts/register_view.html
{% extends "base/base.html" %}
{% block title %}
    {{ product.name }}
{% endblock title %}
{% block main %}
    <div class="container">
        <div class="row">
            <div id="page-content" class="col-12">
                <form action={% url 'accounts:register_view' %} method="post">
                    {% include "components/forms.html" %}
                    <input type="submit" value="register" class="btn btn-primary">
                </form>
            </div>
        </div>
    </div>
{% endblock main %}

backend/accounts/templates/accounts/user_admin_template.html
{% extends "base/base.html" %}
{% block title %}
    User Profile
{% endblock title %}
{% block main %}
    <div class="container text-left" dir='ltr'>
        <div class="row">
            <div class="col-12 col-md-4">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                {% block page_title %}
                                {% endblock page_title %}
                            </div>
                        </div>
                    </div>
                    <div class="col-12 mt-3">
                        <div class="card">
                            <div class="card-body">
                                <ul>
                                    <li>
                                        <a href="{% url 'accounts:user_info_view' %}">Info</a>
                                    </li>
                                    <li>
                                        <a href='#'>Orders</a>
                                    </li>
                                    <li>
                                        <a href='#'>My lists</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'accounts:user_comments_view' %}">Comments</a>
                                    </li>
                                    <li>
                                        <a href='#'>Address</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'accounts:user_logout_view' %}">Logout</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-8">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                {% block content %}
                                {% endblock content %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock main %}

backend/accounts/templates/accounts/user_comments.html
{% extends "accounts/user_admin_template.html" %}
{% block page_title %}
    User Comments
{% endblock page_title %}
{% block content %}
    <div class="row">
        {% for comment in comments %}
            <div class="col-12">
                <h5>{{ commenxt.title }}</h5>
                <span>{{ comment.user.email }}</span>
                <p>{{ comment.text }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

backend/accounts/templates/accounts/user_info.html
{% extends "accounts/user_admin_template.html" %}
{% block page_title %}
User Info
{% endblock page_title %}
{% block content %}

{{form.as_p}}
<div>first name: {{ user.first_name }}</div>
<div>last name: {{ user.last_name }}</div>
<div>Email: {{ user.email }}</div>
<div>Mobile: {{ user.mobile }}</div>
{% endblock content %}

backend/accounts/templates/accounts/view_all_users.html
{% extends "base/base.html" %}
{% block title %}
    users
{% endblock title %}
{% block main %}
    <div class="container">
        <div class="row">
            <div id="page-content" class="col-12 col-md-6 col-lg-4 mx-auto">
                <div class="card-body">
                    {% if perms.accounts.view_user %}
                        <ul>
                            {% for user in users_list %}<li>{{ user.email }}</li>{% endfor %}
                        </ul>
                    {% else %}
                        <div>{{ request.user.email }}</div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock main %}