backend/digikala/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from products.views import home

urlpatterns = [
    path('', home, name='home_view'),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls', namespace='products')),
    path('sellers/', include('sellers.urls', namespace='sellers')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/urls.py
from .views import product_list_view, comment_api_response_rest,\
    ProductListView, ProductClassBaseView, basket_cart_view
from django.urls import path
from .api import ProductDetail, ProductList, ProductListGenericView,\
    ProductDetailGenericView, ProductModelViewSet
from rest_framework import routers

router = routers.SimpleRouter()
router.register(r'products', ProductModelViewSet)

app_name = 'products'
urlpatterns = [
    path('', product_list_view, name='product-list'),
    path('cart/', basket_cart_view, name='basket-cart'),
    path('<int:pk>/comments/', comment_api_response_rest, name='comment_api'),
    path('<int:pk>/', ProductClassBaseView.as_view(), name='product_detail'),
    path('category/<slug:slug>/',
         ProductListView.as_view(), name='product_list'),
] + router.urls

templates/components/mini-card.html
{% load static %}
<nav id="minicart" class="sidebar">
    <div class="dismiss">
        <i class="fas fa-arrow-left"></i>
    </div>
    <div class="sidebar-header">
        <h3>سبد خرید</h3>
    </div>
    <div class="row m-0 totalcart total">
        <div class="col-6 text-right">مجموع خرید:</div>
        <div class="col-6 text-left total-value">25000 تومان</div>
    </div>
    <div class="row m-0 totaloff total">
        <div class="col-6 text-right">مجموع تخفیف:</div>
        <div class="col-6 text-left total-value">1000 تومان</div>
    </div>
    <ul class="p-0 components">
        <li>
            <div class="product-removal">
                <button class="remove-product">
                    <i class="fas fa-window-close jhfg"></i>
                </button>
            </div>
            <a href="#" title="">
                <img src="{% static 'images/products/1.jpg' %}" width="70" height="70" />
            </a>
            <div class="product-title mb-1">
                <a href="#" title="">دستمال کاغذی سافت‌لن</a>
            </div>
            <div class="product-price">
                <del>126,000</del>
                <br>
                <span>170,000 تومان</span>
            </div>
            <div class="product-quantity">
                <div class="input-group">
                    <span class="input-group-btn">
                        <button type="button"
                                class="quantity-left-minus btn btn-danger btn-number"
                                data-type="minus"
                                data-field="">
                            <i class="fas fa-minus"></i>
                        </button>
                    </span>
                    <input type="text"
                           class="quantity"
                           name="quantity"
                           class="form-control input-number"
                           value="10"
                           min="1"
                           max="100">
                    <span class="input-group-btn">
                        <button type="button"
                                class="quantity-right-plus btn btn-success btn-number"
                                data-type="plus"
                                data-field="">
                            <i class="fas fa-plus"></i>
                        </button>
                    </span>
                </div>
            </div>
        </li>
        <li>
            <div class="product-removal">
                <button class="remove-product">
                    <i class="fas fa-window-close jhfg"></i>
                </button>
            </div>
            <a href="#" title="">
                <img src="{% static 'images/products/2.jpg' %}" width="70" height="70" />
            </a>
            <div class="product-title mb-1">
                <a href="#" title="">دستمال کاغذی سافت‌لن</a>
            </div>
            <div class="product-price">
                <del>126,000</del>
                <br>
                <span>170,000 تومان</span>
            </div>
            <div class="product-quantity">
                <div class="input-group">
                    <span class="input-group-btn">
                        <button type="button"
                                class="quantity-left-minus btn btn-danger btn-number"
                                data-type="minus"
                                data-field="">
                            <i class="fas fa-minus"></i>
                        </button>
                    </span>
                    <input type="text"
                           class="quantity"
                           name="quantity"
                           class="form-control input-number"
                           value="10"
                           min="1"
                           max="100">
                    <span class="input-group-btn">
                        <button type="button"
                                class="quantity-right-plus btn btn-success btn-number"
                                data-type="plus"
                                data-field="">
                            <i class="fas fa-plus"></i>
                        </button>
                    </span>
                </div>
            </div>
        </li>
    </ul>
    <button
        class="checkout"
        onclick="window.location.href = '{% url 'products:basket-cart' %}'"
    >
        ثبت سفارش <i class="fas fa-credit-card"></i>
    </button>
</nav>